definitions:
  ginx.PaginatedResp:
    properties:
      count:
        type: integer
      results: {}
    type: object
  ginx.Response:
    properties:
      data: {}
      message:
        type: string
      requestID:
        type: string
    type: object
  multipart.FileHeader:
    properties:
      filename:
        type: string
      header:
        $ref: '#/definitions/textproto.MIMEHeader'
      size:
        type: integer
    type: object
  probe.Result:
    properties:
      core:
        type: boolean
      endpoint:
        type: string
      healthy:
        type: boolean
      issue:
        type: string
      name:
        type: string
    type: object
  serializer.CacheResponse:
    properties:
      digest:
        type: string
      hitCache:
        type: boolean
      timeCost:
        type: number
    type: object
  serializer.CategoryCreateRequest:
    properties:
      name:
        maxLength: 32
        minLength: 1
        type: string
    required:
    - name
    type: object
  serializer.CategoryListResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
      updater:
        type: string
    type: object
  serializer.CategoryRetrieveResponse:
    properties:
      createdAt:
        type: string
      creator:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
      updater:
        type: string
    type: object
  serializer.CategoryUpdateRequest:
    properties:
      name:
        maxLength: 32
        minLength: 1
        type: string
    required:
    - name
    type: object
  serializer.CreateDirRequest:
    properties:
      dirPath:
        type: string
    required:
    - dirPath
    type: object
  serializer.EntryCreateRequest:
    properties:
      categoryID:
        type: integer
      desc:
        type: string
      name:
        maxLength: 32
        minLength: 1
        type: string
      price:
        type: number
    required:
    - categoryID
    - name
    - price
    type: object
  serializer.EntryListResponse:
    properties:
      categoryID:
        type: integer
      categoryName:
        type: string
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updatedAt:
        type: string
      updater:
        type: string
    type: object
  serializer.EntryRetrieveResponse:
    properties:
      categoryID:
        type: integer
      categoryName:
        type: string
      createdAt:
        type: string
      creator:
        type: string
      desc:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updatedAt:
        type: string
      updater:
        type: string
    type: object
  serializer.EntryUpdateRequest:
    properties:
      categoryID:
        type: integer
      desc:
        type: string
      name:
        maxLength: 32
        minLength: 1
        type: string
      price:
        type: number
    required:
    - name
    - price
    type: object
  serializer.HealthzResponse:
    properties:
      fatal:
        type: boolean
      healthy:
        type: boolean
      results:
        items:
          $ref: '#/definitions/probe.Result'
        type: array
      time:
        type: string
    type: object
  serializer.PeriodicTaskCreateRequest:
    properties:
      args:
        items: {}
        type: array
      cron:
        type: string
      name:
        type: string
    type: object
  serializer.PeriodicTaskListResponse:
    properties:
      args:
        type: string
      creator:
        type: string
      cron:
        type: string
      enabled:
        type: boolean
      id:
        type: integer
      name:
        type: string
    type: object
  serializer.SendEmailRequest:
    properties:
      content:
        type: string
      receiver:
        type: string
      title:
        type: string
    required:
    - content
    - receiver
    - title
    type: object
  serializer.TaskCreateRequest:
    properties:
      args:
        items: {}
        type: array
      name:
        type: string
    type: object
  serializer.TaskListResponse:
    properties:
      args:
        type: string
      creator:
        type: string
      duration:
        type: number
      id:
        type: integer
      name:
        type: string
      result:
        type: string
      startedAt:
        type: string
    type: object
  serializer.UploadObjectRequest:
    properties:
      dirPath:
        type: string
      file:
        $ref: '#/definitions/multipart.FileHeader'
    type: object
  serializer.VersionResponse:
    properties:
      buildTime:
        type: string
      gitCommit:
        type: string
      goVersion:
        type: string
      tmplVersion:
        type: string
      version:
        type: string
    type: object
  textproto.MIMEHeader:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
info:
  contact: {}
  description: 蓝鲸开发者中心 SaaS 后台 API 文档
  title: BkApp API DOC
  version: 1.0.0
paths:
  /api/cache:
    get:
      parameters:
      - description: 待哈希数据
        in: query
        name: message
        required: true
        type: string
      - description: 缓存类型，可选值：redis、memory
        in: query
        name: backend
        required: true
        type: string
      - description: 缓存过期时间（单位：秒）
        in: query
        name: expire
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  $ref: '#/definitions/serializer.CacheResponse'
              type: object
      summary: 缓存示例
      tags:
      - cache
  /api/categories:
    get:
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/serializer.CategoryListResponse'
                  type: array
              type: object
      summary: 获取分类列表
      tags:
      - crud
    post:
      parameters:
      - description: 创建分类请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.CategoryCreateRequest'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 创建分类
      tags:
      - crud
  /api/categories/{id}:
    delete:
      parameters:
      - description: 分类 ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: 删除分类
      tags:
      - crud
    get:
      parameters:
      - description: 分类 ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  $ref: '#/definitions/serializer.CategoryRetrieveResponse'
              type: object
      summary: 获取单个分类
      tags:
      - crud
    put:
      parameters:
      - description: 分类 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新分类请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.CategoryUpdateRequest'
      responses:
        "204":
          description: No Content
      summary: 更新分类
      tags:
      - crud
  /api/emails:
    post:
      parameters:
      - description: 邮件配置
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.SendEmailRequest'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 发送邮件
      tags:
      - cloud-api
  /api/entries:
    get:
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/ginx.PaginatedResp'
                  - properties:
                      results:
                        items:
                          $ref: '#/definitions/serializer.EntryListResponse'
                        type: array
                    type: object
              type: object
      summary: 获取条目列表
      tags:
      - crud
    post:
      parameters:
      - description: 创建条目请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.EntryCreateRequest'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 创建条目
      tags:
      - crud
  /api/entries/{id}:
    delete:
      parameters:
      - description: 条目 ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: 删除条目
      tags:
      - crud
    get:
      parameters:
      - description: 条目 ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  $ref: '#/definitions/serializer.EntryRetrieveResponse'
              type: object
      summary: 获取单个条目
      tags:
      - crud
    put:
      parameters:
      - description: 条目 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新条目请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.EntryUpdateRequest'
      responses:
        "204":
          description: No Content
      summary: 更新条目
      tags:
      - crud
  /api/obj-storage/dirs:
    delete:
      parameters:
      - in: query
        name: dirPath
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: 删除目录
      tags:
      - object-storage
    post:
      parameters:
      - description: 创建目录请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.CreateDirRequest'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 创建目录
      tags:
      - object-storage
  /api/obj-storage/objects:
    delete:
      parameters:
      - in: query
        name: dirPath
        type: string
      - in: query
        name: objName
        type: string
      responses:
        "204":
          description: No Content
      summary: 删除已上传对象
      tags:
      - object-storage
    get:
      parameters:
      - in: query
        name: dirPath
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/ginx.PaginatedResp'
                  - properties:
                      results:
                        items:
                          $ref: '#/definitions/serializer.CategoryListResponse'
                        type: array
                    type: object
              type: object
      summary: 获取已上传对象列表
      tags:
      - object-storage
    post:
      parameters:
      - description: 上传对象请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.UploadObjectRequest'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 上传对象
      tags:
      - object-storage
  /api/obj-storage/objects/download:
    get:
      parameters:
      - in: query
        name: dirPath
        type: string
      - in: query
        name: objName
        type: string
      responses:
        "200":
          description: 文件内容
          schema:
            type: file
      summary: 下载对象
      tags:
      - object-storage
  /api/periodic-tasks:
    get:
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/serializer.PeriodicTaskListResponse'
                  type: array
              type: object
      summary: 获取定时任务列表
      tags:
      - async-task
    post:
      parameters:
      - description: 定时任务配置
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.PeriodicTaskCreateRequest'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 创建定时任务
      tags:
      - async-task
  /api/periodic-tasks/{id}:
    delete:
      parameters:
      - description: 定时任务 ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: 删除定时任务
      tags:
      - async-task
  /api/periodic-tasks/{id}/enabled:
    put:
      parameters:
      - description: 定时任务 ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      summary: 切换定时任务启用状态
      tags:
      - async-task
  /api/tasks:
    get:
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/ginx.PaginatedResp'
                  - properties:
                      results:
                        items:
                          $ref: '#/definitions/serializer.TaskListResponse'
                        type: array
                    type: object
              type: object
      summary: 获取任务列表
      tags:
      - async-task
    post:
      parameters:
      - description: 异步任务配置
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/serializer.TaskCreateRequest'
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: 创建异步任务
      tags:
      - async-task
  /healthz:
    get:
      parameters:
      - description: healthz api token
        in: query
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.HealthzResponse'
      summary: 提供服务健康状态
      tags:
      - basic
  /language:
    put:
      responses:
        "204":
          description: No Content
      summary: 修改语言
      tags:
      - basic
  /metrics:
    get:
      parameters:
      - description: metrics api token
        in: query
        name: token
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Prometheus 指标
      tags:
      - basic
  /ping:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 服务探活
      tags:
      - basic
  /version:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.VersionResponse'
      summary: 服务版本信息
      tags:
      - basic
swagger: "2.0"
