/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - Go 开发框架 (BlueKing - Go Framework) available.
 * Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *	https://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */

// Package basic ...
package basic

import (
	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/TencentBlueKing/blueapps-go/pkg/apis/basic/handler"
	"github.com/TencentBlueKing/blueapps-go/pkg/config"
	// docs is generated by Swag CLI, you have to import it.
	_ "github.com/TencentBlueKing/blueapps-go/pkg/docs"
	"github.com/TencentBlueKing/blueapps-go/pkg/middleware"
)

// Register ...
func Register(router *gin.Engine) {
	// basic
	router.GET("/ping", handler.Ping)
	router.GET("/version", handler.Version)
	router.PUT("/language", handler.Language)

	// healthz
	healthzRouter := router.Group("/healthz")
	healthzRouter.Use(middleware.QueryTokenAuth(config.G.Service.HealthzToken))
	healthzRouter.GET("", handler.Healthz)

	// metrics
	metricRouter := router.Group("/metrics")
	metricRouter.Use(middleware.QueryTokenAuth(config.G.Service.MetricToken))
	metricRouter.GET("", gin.WrapH(promhttp.Handler()))

	// swagger docs（仅推荐开发环境使用）
	if config.G.Service.EnableSwagger {
		router.StaticFile("/swagger.json", config.G.Service.ApiDocFileBaseDir+"/swagger.json")
		router.GET(
			"/swagger-ui/*any",
			ginSwagger.WrapHandler(swaggerFiles.Handler, ginSwagger.URL("/swagger.json")),
		)
	}
}
